# Generated by Django 2.1.7 on 2019-05-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imege',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
