# Generated by Django 2.1.7 on 2019-05-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_message_imege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='imege',
            new_name='image',
        ),
    ]
